//
//  RoutineLibrary.swift
//  Pulse Cue
//
//  Which routines a user can actually pick and start.
//
//  Not every `Routine` row is one. Quick Plan materialises a
//  `.workoutGenerated` routine purely so the Runner has something persistent
//  to attach a Session to; it is deliberately kept out of the library, out of
//  search, and out of the picker. Only `.userSaved` routines are offered.
//
//  That rule was previously spelled out separately in `WorkoutView`,
//  `RoutinePickerSheet` and Home, and the copies drifted: Home counted *all*
//  routines to decide whether to show "ワークアウトを開始", so a user whose
//  only routine was generated by Quick Plan got a Start button that opened an
//  empty picker. The button was not wrong about the data; it was asking a
//  different question than the screen it led to.
//
//  One definition, used by every caller, so the button and the list it opens
//  can no longer disagree.
//

import Foundation

enum RoutineLibrary {

    /// The routines that may be listed and started.
    static func startable(from routines: [Routine]) -> [Routine] {
        routines.filter { $0.origin == .userSaved }
    }

    /// Whether there is anything to start.
    ///
    /// The question Home's Start CTA must ask. Counting rows instead is the
    /// bug this exists to prevent.
    static func hasStartable(_ routines: [Routine]) -> Bool {
        routines.contains { $0.origin == .userSaved }
    }
}
